# Generated by Django 4.2.1 on 2023-05-24 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=20)),
                ('admin_password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=50)),
                ('student_id', models.IntegerField(unique=True, validators=[
                 django.core.validators.MaxValueValidator(99999999)])),
                ('student_last_name', models.CharField(max_length=50)),
                ('student_address', models.CharField(max_length=500)),
                ('student_phone', models.CharField(max_length=11, unique=True)),
                ('student_email', models.CharField(max_length=50, unique=True)),
                ('student_level', models.IntegerField(validators=[
                 django.core.validators.MaxValueValidator(4)])),
                ('student_gpa', models.DecimalField(
                    decimal_places=2, max_digits=3)),
                ('student_dep', models.CharField(choices=[('general', 'General'), ('computer science', 'Computer Science'), ('information system', 'Information System'), (
                    'internet technology', 'Internet Technology'), ('artificial intelligence', 'Artificial Intelligence'), ('decision support', 'Decision Support')], max_length=50)),
                ('student_gender', models.CharField(choices=[
                 ('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('student_status', models.CharField(choices=[
                 ('acive', 'Active'), ('inactive', 'Inactive')], max_length=8)),
                ('student_naitonal_id', models.CharField(
                    max_length=14, unique=True)),
                ('student_landline', models.CharField(
                    blank=True, max_length=10, null=True)),
                ('student_dob', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
    ]
