# Generated by Django 4.2.1 on 2023-05-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
