# Generated by Django 4.2.1 on 2023-05-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_dep',
            field=models.CharField(choices=[('General', 'general'), ('Computer science', 'computer Science'), ('Information system', 'information System'), ('Internet technology', 'internet Technology'), ('Artificial Intelligence', 'artificial intelligence'), ('Decision Support', 'decision support')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], max_length=8),
        ),
    ]
