# Generated by Django 4.2.1 on 2023-06-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs_app', '0002_admin_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8),
        ),
    ]
